# config/meta.yml

meta_product_name: "Blackpink - Niwe Couture"
meta_title: "Blackpink - Niwe Couture"
meta_description: "We are a platform of Fashion curators that enables style access"
meta_image: "ufo-landing-page.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
